/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeSimpleRouteImport } from './routes/home-simple'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedMakePicksRouteImport } from './routes/_authenticated/make-picks'
import { Route as AuthenticatedLeaguesRouteImport } from './routes/_authenticated/leagues'
import { Route as AuthenticatedJoinLeagueRouteImport } from './routes/_authenticated/join-league'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateLeagueRouteImport } from './routes/_authenticated/create-league'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSimpleRoute = HomeSimpleRouteImport.update({
  id: '/home-simple',
  path: '/home-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMakePicksRoute = AuthenticatedMakePicksRouteImport.update({
  id: '/make-picks',
  path: '/make-picks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaguesRoute = AuthenticatedLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinLeagueRoute = AuthenticatedJoinLeagueRouteImport.update({
  id: '/join-league',
  path: '/join-league',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateLeagueRoute =
  AuthenticatedCreateLeagueRouteImport.update({
    id: '/create-league',
    path: '/create-league',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/home-simple': typeof HomeSimpleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-league': typeof AuthenticatedCreateLeagueRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join-league': typeof AuthenticatedJoinLeagueRoute
  '/leagues': typeof AuthenticatedLeaguesRoute
  '/make-picks': typeof AuthenticatedMakePicksRoute
  '/stats': typeof AuthenticatedStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/home-simple': typeof HomeSimpleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-league': typeof AuthenticatedCreateLeagueRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join-league': typeof AuthenticatedJoinLeagueRoute
  '/leagues': typeof AuthenticatedLeaguesRoute
  '/make-picks': typeof AuthenticatedMakePicksRoute
  '/stats': typeof AuthenticatedStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/home': typeof HomeRoute
  '/home-simple': typeof HomeSimpleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/create-league': typeof AuthenticatedCreateLeagueRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/join-league': typeof AuthenticatedJoinLeagueRoute
  '/_authenticated/leagues': typeof AuthenticatedLeaguesRoute
  '/_authenticated/make-picks': typeof AuthenticatedMakePicksRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/home-simple'
    | '/login'
    | '/register'
    | '/create-league'
    | '/dashboard'
    | '/join-league'
    | '/leagues'
    | '/make-picks'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/home-simple'
    | '/login'
    | '/register'
    | '/create-league'
    | '/dashboard'
    | '/join-league'
    | '/leagues'
    | '/make-picks'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/home'
    | '/home-simple'
    | '/login'
    | '/register'
    | '/_authenticated/create-league'
    | '/_authenticated/dashboard'
    | '/_authenticated/join-league'
    | '/_authenticated/leagues'
    | '/_authenticated/make-picks'
    | '/_authenticated/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HomeRoute: typeof HomeRoute
  HomeSimpleRoute: typeof HomeSimpleRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-simple': {
      id: '/home-simple'
      path: '/home-simple'
      fullPath: '/home-simple'
      preLoaderRoute: typeof HomeSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/make-picks': {
      id: '/_authenticated/make-picks'
      path: '/make-picks'
      fullPath: '/make-picks'
      preLoaderRoute: typeof AuthenticatedMakePicksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leagues': {
      id: '/_authenticated/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof AuthenticatedLeaguesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join-league': {
      id: '/_authenticated/join-league'
      path: '/join-league'
      fullPath: '/join-league'
      preLoaderRoute: typeof AuthenticatedJoinLeagueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-league': {
      id: '/_authenticated/create-league'
      path: '/create-league'
      fullPath: '/create-league'
      preLoaderRoute: typeof AuthenticatedCreateLeagueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCreateLeagueRoute: typeof AuthenticatedCreateLeagueRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJoinLeagueRoute: typeof AuthenticatedJoinLeagueRoute
  AuthenticatedLeaguesRoute: typeof AuthenticatedLeaguesRoute
  AuthenticatedMakePicksRoute: typeof AuthenticatedMakePicksRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateLeagueRoute: AuthenticatedCreateLeagueRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJoinLeagueRoute: AuthenticatedJoinLeagueRoute,
  AuthenticatedLeaguesRoute: AuthenticatedLeaguesRoute,
  AuthenticatedMakePicksRoute: AuthenticatedMakePicksRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HomeRoute: HomeRoute,
  HomeSimpleRoute: HomeSimpleRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
